baseURL = "https://Siren.Cafe/"
title = "Siren Cafe"
languageCode = "en-us"
theme = "siren.cafe-2018"

googleAnalytics = "UA-121329020-1"
disqusShortname = ""

enableEmoji = true

[params]
	author = "Ricardo N Feliciano"
	profilepic = "/assets/img/logo-circle.svg"
	description = "A blog for Starbucks and Coffee lovers."
	githubUsername = "felicianotech"
	hightlight = true
	highlightStyle = "solarized-dark"
	highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[blackfriday]
	hrefTargetBlank	=	true

[social]
	twitter = "SirenCafeHQ"


[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Newsletter"
	url		= "/newsletter/"
	weight	= 10


#[[menu.social]]
#	name = "twitter"
#	url = "https://twitter.com/SirenCafeHQ/"
#	weight	= -1

[[menu.social]]
    name = "facebook"
    url = "https://www.facebook.com/SirenCafeHQ"
	weight	= 5

[[menu.social]]
    name = "github"
    url = "https://github.com/felicianotech/siren.cafe"
	weight	= 10
